### PR TITLE
Feature/management plus character in topic

### PR DESCRIPTION
**Pull request by frazzaglia**
Add unsubrscibe method in order to unsubscribe from a specific topic.
Add management for plus character in topic string.

### CODE REVIEW

**Comment by shellus** [comment]
nice

**Comment by frazzaglia** [comment]
Please Add a new tag in order to download the updated code with "bower install angular-mqtt".
Thanks in advance.

**Comment by shellus** [comment]
done

**Comment by frazzaglia** [comment]
If you want you can merge the new feature in master branch.

**Comment by shellus** [comment]
sorry, I do not know

**Comment by frazzaglia** [comment]
Try this:
`git fetch --tags origin`
`git checkout master`
`git merge 1.0.2`

**Comment by shellus** [comment]
```
C:\data\www\angular-MQTT>git fetch --tags origin

C:\data\www\angular-MQTT>git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

C:\data\www\angular-MQTT>git merge 1.0.2
Already up-to-date.

C:\data\www\angular-MQTT>git branch
* master

C:\data\www\angular-MQTT>git push --tags
Everything up-to-date

C:\data\www\angular-MQTT>

```

repository only master branch

**Comment by shellus** [comment]
https://github.com/shellus/angular-MQTT/invitations

**Comment by frazzaglia** [comment]
Perfect! Now in master branch there are all lastest updates.
Thanks.

**Pull request merged**
